baseURL = "https://jackbmontgomery.com"
defaultContentLanguage = "en"
# Automatically generate robots.txt
enableRobotsTXT = true
languageCode = "en"
theme = "gokarna"
title = "Jack Montgomery"

[params]
    avatarUrl = "/images/profile.webp"
    avatarAltText = "avatar"
    avatarSize = "size-m"

    description = "Sky above, sand below and peace within"

    socialIcons = [
    {name = "linkedin", url = "https://example.com"},
    {name="github", url="https://example.com"},
    {name="email", url="https://example.com"},
  ]

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2