baseURL = "https://jackbmontgomery.com"
defaultContentLanguage = "en"
# Automatically generate robots.txt
enableRobotsTXT = true
languageCode = "en"
theme = "gokarna"
title = "Jack Montgomery"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
    avatarUrl = "/images/profile.webp"
    avatarAltText = "avatar"
    avatarSize = "size-m"

    newPage = true

    description = "Sky above, sand below and peace within"

    socialIcons = [
    {name = "linkedin", url = "www.linkedin.com/in/jack-b-montgomery"},
    {name="github", url="https://github.com/jackbmontgomery"},
    {name="email", url="mailto:mail@jackbmontgomery.com"},
  ]

  math = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "CV"
    url = "pdfs/CV.pdf"
    weight = 3
    [menu.main.params]
      newPage = true